---
#These tasks will try to execute building steps on packages in $package variable
- name: Configure dependencies
  shell: "{{package.configure}} chdir={{package.dest}}"
  when: package.configure is defined
  tags:
    - build

- name: Execute make commands
  shell: "{{package.make}} chdir={{package.dest}}"
  when: package.make is defined
  tags:
    - build

- name: Install packages from source
  sudo: true
  shell: "{{package.install}} chdir={{package.dest}}"
  when: package.install is defined
  tags:
    - build

