---
#These tasks will try to execute building steps on items in $packages variable
- name: Configure dependancies
  shell: ${item.configure} chdir={{item.dest}}
  when: item.configure is defined
  with_items: $packages

- name: Execute make commands
  shell: ${item.make} chdir={{item.dest}}
  when: item.make is defined
  with_items: $packages

- name: Install packages from source
  sudo: true
  shell: ${item.install} chdir={{item.dest}}
  when: item.install is defined
  with_items: $packages

