---
# For now just preffer the package version
- include: backport.yml
  when: asterisk_install_method=='backport'

- include: source.yml
  when: asterisk_install_method=='source'

- include: package.yml
  when: asterisk_install_method=='package'

- name: Ensure Asterisk directories exist
  sudo: yes
  file: path={{item}} state=directory owner={{asterisk_user}} group={{asterisk_group}} recurse=yes
  with_items:
    - /usr/lib/asterisk
    - /var/lib/asterisk
    - /var/spool/asterisk
    - /var/log/asterisk
    - /var/run/asterisk
    - /etc/asterisk
  tags:
    - build

- name: Ensure asterisk is executable
  sudo: yes
  file: path=/usr/local/bin/asterisk src=/usr/sbin/asterisk state=link owner={{asterisk_user}} group={{asterisk_group}}
  notify: start asterisk
  tags:
    - build

- name: Fix DAHDI configs
  sudo: yes
  lineinfile: dest=/etc/udev/rules.d/dahdi.rules regexp="^SUBSYSTEM==\"dahdi\"" line="SUBSYSTEM==\"dahdi\", OWNER=\"{{asterisk_user}}\", GROUP=\"{{asterisk_group}}\", MODE=\"0660\"" state=present
  tags:
    - build

- name: Do ldconfig
  shell: sudo ldconfig
  tags:
    - build

- name: Ensure odbc.ini is correct
  sudo: yes
  template: dest=/etc/{{item}} src={{item}}.j2
  with_items:
    - odbc.ini
  tags:
    - build
    - config

- name: Ensure odbcinst is correctly configured
  sudo: yes
  shell: "echo \"Name: libmyodbc/addtoodbc\nTemplate: libmyodbc/addtoodbc\nValue: true\nOwners: libmyodbc, libmyodbc:amd64\nFlags: seen\" > /tmp/dpkg.conf && DEBCONF_DB_OVERRIDE='File{/tmp/dpkg.conf}' dpkg-reconfigure -fnoninteractive libmyodbc"
  tags:
    - build
    - config

- name: Ensure db user exists
  mysql_user: name={{asterisk_db_user}} password={{asterisk_db_pass}} priv='{{asterisk_db_name}}.*:all' host={{asterisk_db_scope}}

- name: Ensure db exists
  mysql_db: name={{asterisk_db_name}} encoding=utf8

