---
# For now just preffer the package version
- include: backport.yml
  when: asterisk_install_method=='backport'

- include: source.yml
  when: asterisk_install_method=='source'

- include: package.yml
  when: asterisk_install_method=='package'

- name: Ensure Asterisk directories exist
  sudo: yes
  file: path={{item}} state=directory owner={{asterisk_user}} group={{asterisk_group}} recurse=yes
  with_items:
    - /usr/lib/asterisk
    - /var/lib/asterisk
    - /var/spool/asterisk
    - /var/log/asterisk
    - /var/run/asterisk
    - /etc/asterisk

