---
- { include: dependencies.yml }

- name: Ensure build directories exists
  sudo: yes
  file: path={{item}} owner={{asterisk_user}} group={{asterisk_group}} recurse=yes state=directory
  with_items:
    - '{{source_dir}}'
    - '{{cache_dir}}'
  tags:
    - build

- { include: aquire.yml,  package: "{{dahdi}}"     }
- { include: aquire.yml,  package: "{{libpri}}"    }
- { include: aquire.yml,  package: "{{pjproject}}" }
- { include: aquire.yml,  package: "{{asterisk}}"  }

- { include: build.yml,   package: "{{dahdi}}"     }
- { include: build.yml,   package: "{{libpri}}"    }
- { include: build.yml,   package: "{{pjproject}}" }
- { include: build.yml,   package: "{{asterisk}}"  }

- name: enable all required music packages
  shell: >
    ./menuselect/menuselect --enable {{item}}
    chdir={{asterisk.dest}}
  with_items: asterisk.music
  tags:
    - music

- name: download music packages
  sudo: yes
  shell: >
    make install
    chdir={{asterisk.dest}}
  tags:
    - music

