---
- { include: dependencies.yml }

- name: Ensure build directories exists
  sudo: yes
  file: path={{item}} owner={{asterisk_user}} group={{asterisk_group}} recurse=yes state=directory
  with_items:
    - $source_dir
    - $cache_dir
  tags:
    - build

- { include: aquire.yml,  package: "{{dahdi}}"     }
- { include: aquire.yml,  package: "{{libpri}}"    }
- { include: aquire.yml,  package: "{{pjproject}}" }
- { include: aquire.yml,  package: "{{asterisk}}"  }

- { include: build.yml,   package: "{{dahdi}}"     }
- { include: build.yml,   package: "{{libpri}}"    }
- { include: build.yml,   package: "{{pjproject}}" }
- { include: build.yml,   package: "{{asterisk}}"  }

- name: Fix DAHDI configs
  sudo: yes
  lineinfile: dest=/etc/udev/rules.d/dahdi.rules regexp="^SUBSYSTEM==\"dahdi\"" line="SUBSYSTEM==\"dahdi\", OWNER=\"{{asterisk_user}}\", GROUP=\"{{asterisk_group}}\", MODE=\"0660\"" state=present
  tags:
    - build

- name: Do ldconfig
  shell: sudo ldconfig
  tags:
    - build

- name: Ensure odbc.ini is correct
  sudo: yes
  template: dest=/etc/{{item}} src={{item}}.j2
  with_items:
    - odbc.ini
  tags:
    - build
    - config

- name: Ensure odbcinst is correctly configured
  sudo: yes
  shell: "echo \"Name: libmyodbc/addtoodbc\nTemplate: libmyodbc/addtoodbc\nValue: true\nOwners: libmyodbc, libmyodbc:amd64\nFlags: seen\" > /tmp/dpkg.conf && DEBCONF_DB_OVERRIDE='File{/tmp/dpkg.conf}' dpkg-reconfigure -fnoninteractive libmyodbc"
  tags:
    - build
    - config

- name: Ensure db user exists
  mysql_user: name={{asterisk_db_user}} password={{asterisk_db_pass}} priv='{{asterisk_db_name}}.*:all' host={{asterisk_db_scope}}

- name: Ensure db exists
  mysql_db: name={{asterisk_db_name}} encoding=utf8

